# Generated by Django 3.2.6 on 2022-08-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=200)),
                ('player_one', models.CharField(default='', max_length=200)),
                ('player_two', models.CharField(default='', max_length=200)),
                ('record', models.CharField(default='0-0', max_length=200)),
                ('winning_percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('value_for_order', models.IntegerField()),
                ('team_image', models.FilePathField(path='media/images/')),
            ],
            options={
                'verbose_name': 'Teams',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='game_team_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.CharField(default='0', max_length=200)),
                ('game_team_two_score', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=200)),
                ('loser', models.CharField(max_length=200)),
                ('team_two_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cornholehome.teams')),
            ],
        ),
        migrations.CreateModel(
            name='game_team_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.CharField(default='0', max_length=200)),
                ('game_team_one_score', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=200)),
                ('loser', models.CharField(max_length=200)),
                ('team_one_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cornholehome.teams')),
            ],
        ),
        migrations.CreateModel(
            name='game_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.CharField(default='0', max_length=200)),
                ('game_team_one_score', models.IntegerField(default=0)),
                ('game_team_two_score', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=200)),
                ('loser', models.CharField(max_length=200)),
                ('team_one_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team One+', to='cornholehome.teams')),
                ('team_two_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team Two+', to='cornholehome.teams')),
            ],
        ),
    ]
