# Generated by Django 3.2.6 on 2022-08-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.CharField(default='0', max_length=200)),
                ('game_team_one_score', models.IntegerField(default=0)),
                ('game_team_two_score', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=200)),
                ('loser', models.CharField(max_length=200)),
                ('team_one_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team One+', to='cornholehome.teams')),
                ('team_two_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team Two+', to='cornholehome.teams')),
            ],
        ),
        migrations.DeleteModel(
            name='game_model',
        ),
    ]
