# Generated by Django 3.2.6 on 2022-08-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0002_auto_20220816_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='value_for_order',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='teams',
            name='winning_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
