# Generated by Django 3.2.6 on 2022-08-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0003_auto_20220816_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='teamname',
            field=models.CharField(max_length=15),
        ),
    ]
