# Generated by Django 3.2.6 on 2022-08-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0004_alter_teams_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='total_win_value',
            field=models.IntegerField(default=99),
        ),
    ]
