# Generated by Django 3.2.6 on 2022-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0006_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_team_two',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='league_team_two_record',
            field=models.CharField(default='0-0', max_length=20),
        ),
    ]
