# Generated by Django 3.2.6 on 2022-08-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0008_remove_league_link_to_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='link_to_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cornholehome.league'),
        ),
    ]
