# Generated by Django 3.2.6 on 2022-08-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0010_auto_20220826_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='link_to_league',
        ),
    ]
