# Generated by Django 3.2.6 on 2022-08-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0011_remove_league_link_to_league'),
    ]

    operations = [
        migrations.DeleteModel(
            name='league',
        ),
    ]
