# Generated by Django 3.2.6 on 2022-08-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0012_delete_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=200)),
                ('league_team', models.CharField(max_length=15)),
                ('league_team_record', models.CharField(default='0-0', max_length=20)),
                ('link_to_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cornholehome.teams')),
            ],
        ),
    ]
