# Generated by Django 3.2.6 on 2022-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0013_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='league_placeholder',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
