# Generated by Django 3.2.6 on 2022-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0014_teams_league_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_name_placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=200)),
            ],
        ),
    ]
