# Generated by Django 3.2.6 on 2022-09-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0015_league_name_placeholder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='league_name_placeholder',
        ),
    ]
