# Generated by Django 3.2.6 on 2022-09-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0018_league_value_for_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='value_for_order',
        ),
    ]
