# Generated by Django 3.2.6 on 2022-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0019_remove_league_value_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='value_for_order_league',
            field=models.IntegerField(default=99),
        ),
    ]
