# Generated by Django 3.2.6 on 2022-09-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornholehome', '0020_league_value_for_order_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='winning_percentage_league',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
